version: '3.8'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - '5432:5432'

    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'

    redis:
        image: redis:7.0.4-alpine
        restart: always
        ports:
        - '6379:6379'

    mailhog:
        image: mailhog/mailhog
        ports:
        - '1025:1025' # smtp
        - '8025:8025' # web ui